export const tenantsData = [
  {
    id: 1,
    name: "Mubarak Muhammad",
    creationDate: "2021-08-01",
    active: true,
    dataUsage: 120,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
  {
    id: 2,
    name: "Hafiz Muhammad",
    creationDate: "2022-02-14",
    active: false,
    dataUsage: 85,
    subscription: "Standard",
    billingCycle: "Yearly",
  },
  {
    id: 3,
    name: "Fatima Muhammad",
    creationDate: "2023-06-21",
    active: true,
    dataUsage: 150,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    id: 4,
    name: "Abida Muhammad",
    creationDate: "2023-06-21",
    active: true,
    dataUsage: 95,
    subscription: "Basic",
    billingCycle: "Quarterly",
  },
  {
    id: 5,
    name: "Jamila Muhammad",
    creationDate: "2023-06-21",
    active: true,
    dataUsage: 110,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    id: 6,
    name: "Hafsah Muhammad",
    creationDate: "2023-06-21",
    active: true,
    dataUsage: 60,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    id: 7,
    name: "Azizatu Muhammad",
    creationDate: "2023-06-21",
    active: false,
    dataUsage: 40,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    id: 8,
    name: "Linda Taylor",
    creationDate: "2022-03-10",
    active: true,
    dataUsage: 130,
    subscription: "Enterprise",
    billingCycle: "Yearly",
  },
  {
    id: 9,
    name: "Robert Anderson",
    creationDate: "2021-09-01",
    active: true,
    dataUsage: 200,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
  {
    id: 10,
    name: "Maria Thomas",
    creationDate: "2020-01-15",
    active: false,
    dataUsage: 55,
    subscription: "Basic",
    billingCycle: "Quarterly",
  },
  {
    id: 11,
    name: "William Jackson",
    creationDate: "2021-11-25",
    active: true,
    dataUsage: 170,
    subscription: "Standard",
    billingCycle: "Yearly",
  },
  {
    id: 12,
    name: "Elizabeth Harris",
    creationDate: "2023-01-05",
    active: true,
    dataUsage: 140,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    id: 13,
    name: "Christopher Martin",
    creationDate: "2022-10-11",
    active: true,
    dataUsage: 190,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    id: 14,
    name: "Patricia Lee",
    creationDate: "2021-02-08",
    active: false,
    dataUsage: 65,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    id: 15,
    name: "Daniel Walker",
    creationDate: "2023-03-18",
    active: true,
    dataUsage: 125,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    id: 16,
    name: "Nancy Hall",
    creationDate: "2021-07-30",
    active: false,
    dataUsage: 30,
    subscription: "Basic",
    billingCycle: "Yearly",
  },
  {
    id: 17,
    name: "Mark Allen",
    creationDate: "2020-05-12",
    active: true,
    dataUsage: 220,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    id: 18,
    name: "Susan Young",
    creationDate: "2022-11-22",
    active: false,
    dataUsage: 75,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    id: 19,
    name: "Joseph King",
    creationDate: "2023-02-28",
    active: true,
    dataUsage: 180,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    id: 20,
    name: "Karen Wright",
    creationDate: "2023-04-07",
    active: false,
    dataUsage: 50,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    id: 21,
    name: "Steven Scott",
    creationDate: "2022-05-13",
    active: true,
    dataUsage: 145,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    id: 22,
    name: "Deborah Green",
    creationDate: "2021-12-06",
    active: false,
    dataUsage: 35,
    subscription: "Basic",
    billingCycle: "Yearly",
  },
  {
    id: 23,
    name: "Larry Adams",
    creationDate: "2023-02-17",
    active: true,
    dataUsage: 160,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    id: 24,
    name: "Betty Nelson",
    creationDate: "2022-08-25",
    active: false,
    dataUsage: 45,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    id: 25,
    name: "James Carter",
    creationDate: "2023-05-30",
    active: true,
    dataUsage: 175,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
    {
    id: 25,
    name: "James Carter",
    creationDate: "2023-05-30",
    active: true,
    dataUsage: 175,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
];
